pipeline {
    agent any
    stages{
        stage('Install Maven'){
            steps{
                tool name: 'Maven 3.9.6', type: 'maven'
            }
        }
        stage('Getting code from git repository'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name:'*/main']], extensions: [], userRemoteConfigs: [[url:'https://github.com/SushmaKankatala/SWE645-hw3.git']]])
            }
        }
        stage('Docker image-Building'){
            steps{
                    sh 'rm -rf *.jar'
                    sh 'ls -R'
                    sh 'docker build -t surveyjar .'
                    sh 'docker image tag surveyjar skankat/surveyjar:latest'
            }
        }
        stage('Pushing the docker image to hub'){
            steps{
                sh 'docker login -u skankat -p Masonchi%04'
                sh 'docker image push skankat/surveyjar:latest'
            }
            
        }
        stage('Deploy to Rancher Cluster'){
            steps{
                sh 'kubectl set image deployment/ranchdep container-swe645=skankat/surveyjar:latest -n ranchspace'

            }
    }
}
}
